server:
  port: 8088
spring:
  application: #应用配置
    name: test #服务名
  datasource: #数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver #驱动
    username: root #登录数据库的用户名和密码
    password: root
    url: jdbc:mysql://127.0.0.1:3306/javastudy?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    #type: com.zaxxer.hikari.HikariDataSource
  #    hikari:
  #      username: root
  #      password: root
  #      jdbc-url: jdbc:mysql://localhost:3306/javastudy?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  #      driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true #同名是否允许覆盖注册
logging: #日志
  level:
    root: debug #打印日志级别